In [50]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set display option to avoid scientific notation in pandas, show up to 5 decimal points
pd.set_option('display.float_format', lambda x: '%.5f' % x)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

In [51]:
# Load the dataset 
flood_data = pd.read_excel("flood_full_data.xlsx")
flood_data.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,Country,Subregion,Region,Location,Origin,Associated Types,OFDA/BHA Response,Appeal,Declaration,AID Contribution ('000 US$),Magnitude,Magnitude Scale,Latitude,Longitude,River Basin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
0,2018-0040-BRA,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),DFO:4576,NaN,BRA,Brazil,Latin America and the Caribbean,Americas,Rio de Janeiro,Heavy rains,Collapse|Flood,No,No,No,NaN,55138.9500,Km2,-22.4790,-44.0950,NaN,2018,2.0000,14.0000,2018,2.0000,16.0000,4.0000,NaN,250.0000,NaN,250.0000,NaN,NaN,NaN,NaN,10000.0000,12492.0000,80.0496,"[{""adm2_code"":9961,""adm2_name"":""Rio De Janeiro""}]","[{""gid_2"":""BRA.19.68_2"",""migration_date"":""2025...",2018-02-20,2025-12-20
1,2022-0770-RWA,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,RWA,Rwanda,Sub-Saharan Africa,Africa,Kigali,NaN,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2022,11.0000,17.0000,2022,11.0000,18.0000,3.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.2946,"[{""adm1_code"":21970,""adm1_name"":""Kigali City/U...","[{""gid_1"":""RWA.5_1"",""migration_date"":""2025-12-...",2022-11-25,2025-12-20
2,2000-0620-NGA,No,nat-hyd-flo-fla,Natural,Hydrological,Flood,Flash flood,NaN,NaN,NGA,Nigeria,Sub-Saharan Africa,Africa,Lagos province,Brief torrential rain,NaN,No,No,No,NaN,7700.0000,Km2,NaN,NaN,NaN,2000,9.0000,20.0000,2000,9.0000,21.0000,NaN,NaN,500.0000,NaN,500.0000,NaN,NaN,NaN,NaN,4805.0000,8753.0000,54.8952,"[{""adm1_code"":2230,""adm1_name"":""Lagos""}]","[{""gid_1"":""NGA.25_1"",""migration_date"":""2025-12...",2005-09-15,2025-12-20
3,2022-0405-PAK,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2022-000270,NaN,PAK,Pakistan,Southern Asia,Asia,"Lasbela, Jhal Magsi, Killa Saifullah, Pishin, ...",Monsoon rain,"Slide (land, mud, snow, rock)|Storm",No,Yes,Yes,NaN,NaN,Km2,NaN,NaN,NaN,2022,6.0000,14.0000,2022,9.0000,14.0000,1739.0000,12865.0000,33000000.0000,NaN,33012865.0000,10000000.0000,10718733.0000,7000.0000,7503.0000,15000000.0000,16078100.0000,93.2946,NaN,NaN,2022-07-07,2023-09-26
4,2022-0347-CIV,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2022-000249,NaN,CIV,Côte d’Ivoire,Sub-Saharan Africa,Africa,"Abobo, Anyama, Attecoubé, Bingerville, Port-Bo...",Heavy rains,"Slide (land, mud, snow, rock)",No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2022,6.0000,16.0000,2022,6.0000,21.0000,13.0000,114.0000,11478.0000,NaN,11592.0000,NaN,NaN,NaN,NaN,NaN,NaN,93.2946,NaN,NaN,2022-06-29,2023-09-26

In [52]:
flood_data.columns

Index(['DisNo.', 'Historic', 'Classification Key', 'Disaster Group', 'Disaster Subgroup', 'Disaster Type',
       'Disaster Subtype', 'External IDs', 'Event Name', 'ISO', 'Country', 'Subregion', 'Region', 'Location', 'Origin',
       'Associated Types', 'OFDA/BHA Response', 'Appeal', 'Declaration', 'AID Contribution ('000 US$)', 'Magnitude',
       'Magnitude Scale', 'Latitude', 'Longitude', 'River Basin', 'Start Year', 'Start Month', 'Start Day', 'End Year',
       'End Month', 'End Day', 'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless', 'Total Affected',
       'Reconstruction Costs ('000 US$)', 'Reconstruction Costs, Adjusted ('000 US$)', 'Insured Damage ('000 US$)',
       'Insured Damage, Adjusted ('000 US$)', 'Total Damage ('000 US$)', 'Total Damage, Adjusted ('000 US$)', 'CPI',
       'Admin Units', 'GADM Admin Units', 'Entry Date', 'Last Update'],
      dtype='object')

In [53]:
flood_data['Start Date'] = pd.to_datetime(flood_data[['Start Year', 'Start Month', 'Start Day']].rename(columns={'Start Year': 'year', 'Start Month': 'month', 'Start Day': 'day'}), errors='coerce')
flood_data['End Date'] = pd.to_datetime(flood_data[['End Year', 'End Month', 'End Day']].rename(columns={'End Year': 'year', 'End Month': 'month', 'End Day': 'day'}), errors='coerce')
flood_data['Duration'] = (flood_data['End Date'] - flood_data['Start Date']).dt.days.astype('Int64')
flood_data.drop(columns=['Start Year', 'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day'], inplace=True)
#order flood by date soonest first
flood_data.sort_values(by='Start Date', inplace=True, ascending=False)
#reset index
flood_data.reset_index(drop=True, inplace=True)
#drop rows with NaT in start and end date
flood_data.dropna(subset=['Start Date', 'End Date'], inplace=True)

In [54]:

#create ID columns
flood_data['Flood_ID'] = flood_data.index + 1
#make flood id fisrt collumns 
cols = flood_data.columns.tolist()
flood_data = flood_data[cols[-1:] + cols[:-1]]

#first 150 rows
flood_extra_data = flood_data.iloc[:150].copy()

flood_extra_data.head()

,Flood_ID,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,Country,Subregion,Region,Location,Origin,Associated Types,OFDA/BHA Response,Appeal,Declaration,AID Contribution ('000 US$),Magnitude,Magnitude Scale,Latitude,Longitude,River Basin,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update,Start Date,End Date,Duration
0,1,2026-0088-SYR,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,SYR,Syrian Arab Republic,Western Asia,Asia,"Idleb, Lattaquié, Hama",Heavy rain,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,3.0000,5.0000,4500.0000,NaN,4505.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-11,2026-02-16,2026-02-08,2026-02-10,2
1,2,2026-0075-IDN,No,nat-hyd-flo-fla,Natural,Hydrological,Flood,Flash flood,NaN,NaN,IDN,Indonesia,South-eastern Asia,Asia,Greater Jakarta area and the Indramayu regency...,Heavy rain,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,"Cilanang, Srenseng and Medana rivers",NaN,NaN,20600.0000,NaN,20600.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-04,2026-02-16,2026-01-28,2026-02-03,6
2,3,2026-0084-COL,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2026-000017,NaN,COL,Colombia,Latin America and the Caribbean,Americas,"Cordoba, Sucre, Cauca, La Guajira, Chocó, and ...",Torrential rain,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,Sinu river,44.0000,NaN,216000.0000,NaN,216000.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-11,2026-02-16,2026-01-26,2026-02-11,16
3,4,2026-0033-TUN,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2026-000006|GLIDE:FL-2026-000008,NaN,TUN,Tunisia,Northern Africa,Africa,"Laghouat, Blida, Djelfa, Mascara, El Bayadh, B...",Heavy rain,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,5.0000,NaN,25000.0000,NaN,25000.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-26,2026-02-04,2026-01-18,2026-01-21,3
4,5,2026-0033-DZA,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2026-000006|GLIDE:FL-2026-000008,NaN,DZA,Algeria,Northern Africa,Africa,"Laghouat, Blida, Djelfa, Mascara, El Bayadh, B...",Heavy rain,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,1.0000,NaN,6000.0000,NaN,6000.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-26,2026-02-04,2026-01-18,2026-01-20,2

In [55]:
flood_extra_data.shape

(150, 45)

In [56]:
# Convert columns to appropriate data types
flood_extra_data['Flood_ID'] = flood_extra_data['Flood_ID'].astype('int64')
flood_extra_data['ISO'] = flood_extra_data['ISO'].astype('string')
flood_extra_data['Country'] = flood_extra_data['Country'].astype('string')
flood_extra_data['Subregion'] = flood_extra_data['Subregion'].astype('string')
flood_extra_data['Region'] = flood_extra_data['Region'].astype('string')
flood_extra_data['River Basin'] = flood_extra_data['River Basin'].astype('string')
flood_extra_data['Duration'] = flood_extra_data['Duration'].astype('Int64') 

#drop all collumns with  50 non-null values
drop_cols = flood_extra_data.columns[flood_extra_data.notnull().sum() < 50]
flood_extra_data = flood_extra_data.drop(columns=drop_cols)
#drop entry date and last update date
flood_extra_data = flood_extra_data.drop(columns=['Entry Date', 'Last Update'])

In [57]:
flood_extra_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 151
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Flood_ID            150 non-null    int64
 1   DisNo.              150 non-null    object
 2   Historic            150 non-null    object
 3   Classification Key  150 non-null    object
 4   Disaster Group      150 non-null    object
 5   Disaster Subgroup   150 non-null    object
 6   Disaster Type       150 non-null    object
 7   Disaster Subtype    150 non-null    object
 8   ISO                 150 non-null    string
 9   Country             150 non-null    string
 10  Subregion           150 non-null    string
 11  Region              150 non-null    string
 12  Location            145 non-null    object
 13  Origin              138 non-null    object
 14  Associated Types    56 non-null     object
 15  OFDA/BHA Response   150 non-null    object
 16  Appeal              150 non-null    object
 17  Declaration         150 non-null    object
 18  Magnitude Scale     150 non-null    object
 19  Total Deaths        117 non-null    float64
 20  No. Injured         54 non-null     float64
 21  No. Affected        131 non-null    float64
 22  Total Affected      139 non-null    float64
 23  Start Date          150 non-null    datetime64[ns]
 24  End Date            150 non-null    datetime64[ns]
 25  Duration            150 non-null    Int64
dtypes: Int64(1), datetime64[ns](2), float64(4), int64(1), object(14), string(4)
memory usage: 31.8+ KB

In [58]:
flood_extra_data.columns

Index(['Flood_ID', 'DisNo.', 'Historic', 'Classification Key', 'Disaster Group', 'Disaster Subgroup', 'Disaster Type',
       'Disaster Subtype', 'ISO', 'Country', 'Subregion', 'Region', 'Location', 'Origin', 'Associated Types',
       'OFDA/BHA Response', 'Appeal', 'Declaration', 'Magnitude Scale', 'Total Deaths', 'No. Injured', 'No. Affected',
       'Total Affected', 'Start Date', 'End Date', 'Duration'],
      dtype='object')

In [26]:
#save to csv
flood_extra_data.to_csv('../Data/Flood_Data/flood_extra_data.csv', index=False)

In [28]:
relevant_columns=['Flood_ID','Disaster Type','Disaster Subtype','ISO', 'Country', 'Subregion', 'Region', 'Location', 'Origin','Associated Types','River Basin', 
                  'Start Date', 'End Date','Duration']

flood_pd=flood_data[relevant_columns].copy()

#reset index
flood_pd.reset_index(drop=True, inplace=True)
#create ID columns

flood_pd.head()

,Flood_ID,Disaster Type,Disaster Subtype,ISO,Country,Subregion,Region,Location,Origin,Associated Types,River Basin,Start Date,End Date,Duration
0,1,Flood,Flood (General),SYR,Syrian Arab Republic,Western Asia,Asia,"Idleb, Lattaquié, Hama",Heavy rain,NaN,NaN,2026-02-08,2026-02-10,2
1,2,Flood,Flash flood,IDN,Indonesia,South-eastern Asia,Asia,Greater Jakarta area and the Indramayu regency...,Heavy rain,NaN,"Cilanang, Srenseng and Medana rivers",2026-01-28,2026-02-03,6
2,3,Flood,Flood (General),COL,Colombia,Latin America and the Caribbean,Americas,"Cordoba, Sucre, Cauca, La Guajira, Chocó, and ...",Torrential rain,NaN,Sinu river,2026-01-26,2026-02-11,16
3,4,Flood,Flood (General),TUN,Tunisia,Northern Africa,Africa,"Laghouat, Blida, Djelfa, Mascara, El Bayadh, B...",Heavy rain,NaN,NaN,2026-01-18,2026-01-21,3
4,5,Flood,Flood (General),DZA,Algeria,Northern Africa,Africa,"Laghouat, Blida, Djelfa, Mascara, El Bayadh, B...",Heavy rain,NaN,NaN,2026-01-18,2026-01-20,2

In [30]:
#flood for common crawl last 150 events
rel_columns=['Flood_ID','ISO', 'Country', 'Subregion', 'Region', 'Location', 'River Basin', 'Start Date', 'End Date','Duration']
#use relevant columns
flood_crawl= flood_pd[rel_columns].iloc[:150].copy()

flood_crawl.columns

Index(['Flood_ID', 'ISO', 'Country', 'Subregion', 'Region', 'Location', 'River Basin', 'Start Date', 'End Date',
       'Duration'],
      dtype='object')

In [31]:
flood_with_lang=pd.read_csv('flood_crawl_with_languages.csv')

#'Language_ISO_639_3', 'Local_Languages' add this columns to flood_crawl
flood_crawl['Language_ISO_639_3'] = flood_with_lang['Language_ISO_639_3']
flood_crawl['Local_Languages'] = flood_with_lang['Local_Languages']

#order of the collumns 
#save to csv
flood_crawl.to_csv('../Data/Flood_Data/flood_crawl.csv', index=False)

In [37]:
# Convert comma-separated strings to lists and strip whitespace
flood_crawl['Location'] = flood_crawl['Location'].apply(lambda x: [loc.strip() for loc in x.split(',')] if pd.notna(x) and isinstance(x, str) else [])
flood_crawl['Language_ISO_639_3'] = flood_crawl['Language_ISO_639_3'].apply(lambda x: [lang.strip() for lang in x.split(',')] if pd.notna(x) and isinstance(x, str) else [])
flood_crawl['Local_Languages'] = flood_crawl['Local_Languages'].apply(lambda x: [lang.strip() for lang in x.split(',')] if pd.notna(x) and isinstance(x, str) else [])

In [42]:
# Convert columns to appropriate data types
flood_crawl['Flood_ID'] = flood_crawl['Flood_ID'].astype('int64')
flood_crawl['ISO'] = flood_crawl['ISO'].astype('string')
flood_crawl['Country'] = flood_crawl['Country'].astype('string')
flood_crawl['Subregion'] = flood_crawl['Subregion'].astype('string')
flood_crawl['Region'] = flood_crawl['Region'].astype('string')
flood_crawl['River Basin'] = flood_crawl['River Basin'].astype('string')
flood_crawl['Duration'] = flood_crawl['Duration'].astype('Int64')  # nullable integer

# Start Date and End Date should already be datetime, but ensure it
flood_crawl['Start Date'] = pd.to_datetime(flood_crawl['Start Date'])
flood_crawl['End Date'] = pd.to_datetime(flood_crawl['End Date'])

# Location, Language_ISO_639_3, and Local_Languages remain as object (lists)
# They're already converted to lists in the previous cell

# Verify the data types
flood_crawl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Flood_ID            150 non-null    int64
 1   ISO                 150 non-null    string
 2   Country             150 non-null    string
 3   Subregion           150 non-null    string
 4   Region              150 non-null    string
 5   Location            150 non-null    object
 6   River Basin         22 non-null     string
 7   Start Date          150 non-null    datetime64[ns]
 8   End Date            150 non-null    datetime64[ns]
 9   Duration            150 non-null    Int64
 10  Language_ISO_639_3  150 non-null    object
 11  Local_Languages     150 non-null    object
dtypes: Int64(1), datetime64[ns](2), int64(1), object(3), string(5)
memory usage: 14.3+ KB

In [40]:
flood_crawl.head()

,Flood_ID,ISO,Country,Subregion,Region,Location,River Basin,Start Date,End Date,Duration,Language_ISO_639_3,Local_Languages
0,1,SYR,Syrian Arab Republic,Western Asia,Asia,"[Idleb, Lattaquié, Hama]",NaN,2026-02-08,2026-02-10,2,[arb],[Arabic]
1,2,IDN,Indonesia,South-eastern Asia,Asia,[Greater Jakarta area and the Indramayu regenc...,"Cilanang, Srenseng and Medana rivers",2026-01-28,2026-02-03,6,[ind],[Indonesian]
2,3,COL,Colombia,Latin America and the Caribbean,Americas,"[Cordoba, Sucre, Cauca, La Guajira, Chocó, and...",Sinu river,2026-01-26,2026-02-11,16,[spa],[Spanish]
3,4,TUN,Tunisia,Northern Africa,Africa,"[Laghouat, Blida, Djelfa, Mascara, El Bayadh, ...",NaN,2026-01-18,2026-01-21,3,[arb],[Arabic]
4,5,DZA,Algeria,Northern Africa,Africa,"[Laghouat, Blida, Djelfa, Mascara, El Bayadh, ...",NaN,2026-01-18,2026-01-20,2,[arb],[Arabic]

In [41]:
flood_crawl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Flood_ID            150 non-null    int64
 1   ISO                 150 non-null    object
 2   Country             150 non-null    object
 3   Subregion           150 non-null    object
 4   Region              150 non-null    object
 5   Location            150 non-null    object
 6   River Basin         22 non-null     object
 7   Start Date          150 non-null    datetime64[ns]
 8   End Date            150 non-null    datetime64[ns]
 9   Duration            150 non-null    Int64
 10  Language_ISO_639_3  150 non-null    object
 11  Local_Languages     150 non-null    object
dtypes: Int64(1), datetime64[ns](2), int64(1), object(8)
memory usage: 14.3+ KB

In [59]:
flood_crawl.columns

Index(['Flood_ID', 'ISO', 'Country', 'Subregion', 'Region', 'Location', 'River Basin', 'Start Date', 'End Date',
       'Duration', 'Language_ISO_639_3', 'Local_Languages'],
      dtype='object')

In [33]:
list_countries = flood_crawl['Country'].unique().tolist()
len(list_countries)
list_countries

['Syrian Arab Republic',
 'Indonesia',
 'Colombia',
 'Tunisia',
 'Algeria',
 'Afghanistan',
 'Zimbabwe',
 'United States of America',
 'Iran (Islamic Republic of)',
 'Morocco',
 'Malaysia',
 'Bolivia (Plurinational State of)',
 'Iraq',
 'Thailand',
 'Democratic Republic of the Congo',
 'Costa Rica',
 'Honduras',
 'Mexico',
 'Nepal',
 'India',
 'Bulgaria',
 'Cambodia',
 'Ukraine',
 'Georgia',
 'Haiti',
 'Gambia',
 'Sierra Leone',
 'Sudan',
 'Uganda',
 'China',
 'Pakistan',
 'Republic of Korea',
 'Central African Republic',
 'Cabo Verde',
 'Japan',
 'Myanmar',
 'Equatorial Guinea',
 'Taiwan (Province of China)',
 'Romania',
 'Nigeria',
 'China, Hong Kong Special Administrative Region',
 "Lao People's Democratic Republic",
 'Bangladesh',
 'South Africa',
 'Viet Nam',
 'Philippines',
 'United Republic of Tanzania',
 'Somalia',
 'Brazil',
 'Croatia',
 'Bosnia and Herzegovina',
 'Italy',
 'Argentina',
 'Peru',
 'Namibia',
 'Botswana',
 'Madagascar',
 'Libya',
 'Kenya',
 'Malawi',
 'Gabon',
 'Spain',
 'Dominican Republic',
 'France',
 'Yemen',
 'Cameroon',
 'Chad',
 'Guinea']